#!/usr/bin/env bash
# hydrate-secrets.sh — Generate .env from macOS Keychain for Game of Memes
# Run before: npm run dev, npm run build, or any deployment.
# Idempotent: safe to re-run at any time. Output is chmod 600.
#
# Keychain entries use account "openclaw" unless noted.
# ElevenLabs uses account "ari" (legacy entry).
#
# Usage: ~/Documents/Github/Game_Of_Memes/scripts/hydrate-secrets.sh

set -euo pipefail

PROJECT_DIR="$(cd "$(dirname "$0")/.." && pwd)"
ENV_FILE="$PROJECT_DIR/.env"
ERRORS=0

pull() {
  local name="$1"
  local acct="${2:-openclaw}"
  local val
  val=$(security find-generic-password -a "$acct" -s "$name" -w 2>/dev/null) || {
    echo "[hydrate] ERROR: $name (account: $acct) not found in Keychain" >&2
    ERRORS=$((ERRORS + 1))
    echo "MISSING_${name}"
    return
  }
  echo "$val"
}

echo "[hydrate] Generating $ENV_FILE from Keychain..."

cat > "$ENV_FILE" << ENVFILE
# === AUTO-GENERATED by hydrate-secrets.sh ===
# Do NOT edit manually. Modify the script or add secrets to Keychain instead.
# Generated: $(date -u +"%Y-%m-%dT%H:%M:%SZ")

# Node
NODE_ENV=development

# Wield / VibeMarket NFT API
WIELD_API_KEY=$(pull "gom-wield-api-key")

# Supabase (Game of Memes dedicated instance)
NEXT_PUBLIC_SUPABASE_URL=https://lbcudodfscgugoekcckq.supabase.co
NEXT_PUBLIC_SUPABASE_ANON_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxiY3Vkb2Rmc2NndWdvZWtjY2txIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzA4Njk0MjUsImV4cCI6MjA4NjQ0NTQyNX0.Hw7ou3ljMWlOZK7OqvRjbKtykmYv_gaidRtEpWO3ewo
SUPABASE_SERVICE_ROLE_KEY=$(pull "gom-supabase-service-role-key")

# Privy
NEXT_PUBLIC_PRIVY_APP_ID=cm2wn112807mht77uaeeury9u
PRIVY_APP_ID=cm2wn112807mht77uaeeury9u
PRIVY_SECRET_KEY=$(pull "privy-secret-key")

# WalletConnect
NEXT_PUBLIC_WALLETCONNECT_PROJECT_ID=$(pull "walletconnect-project-id")
NEXT_PUBLIC_WC_PROJECT_ID=$(pull "walletconnect-project-id")
NEXT_PUBLIC_WALLET_CONNECT_PROJECT_ID=$(pull "walletconnect-project-id")

# Alchemy
NEXT_PUBLIC_ALCHEMY_API_KEY=$(pull "alchemy-api-key")
NEXT_PUBLIC_ALCHEMY_ID=$(pull "alchemy-api-key")

# Network
NEXT_PUBLIC_ENABLE_TESTNETS=true
NEXT_PUBLIC_DEFAULT_CHAIN=base

# Contracts (public addresses, not secrets)
NEXT_PUBLIC_AQUAPRIME_NFT_CONTRACT=0x3e7A0f61A9889BFC6b8A9f356F9CC57299762369
NEXT_PUBLIC_MOONSTONE_CONTRACT=0x491607a777AedAb22e5409820eF5386fBFE7F360

# OpenAI (SERVER-SIDE ONLY — no NEXT_PUBLIC_ prefix)
OPENAI_API_KEY=$(pull "openai-api-key")

# Deepgram (SERVER-SIDE ONLY — no NEXT_PUBLIC_ prefix)
DEEPGRAM_API_KEY=$(pull "deepgram-api-key")

# LiveKit
LIVEKIT_API_KEY=$(pull "livekit-api-key")
LIVEKIT_API_SECRET=$(pull "livekit-api-secret")
NEXT_PUBLIC_LIVEKIT_URL=wss://aquaprime-2tcbpf6q.livekit.cloud
NEXT_PUBLIC_AUTHORIZED_ADDRESSES=0x2026bd9b69593A4002E87049deA6c724654DC38b,0xabcdefabcdefabcdefabcdefabcdefabcdefabcd

# ElevenLabs (Keychain account: "ari")
ELEVEN_LABS_API_KEY=$(pull "elevenlabs-api-key" "ari")

# JWT / API
JWT_SECRET=$(pull "jwt-secret")
API_HOSTNAME=https://n72lfbogf6.execute-api.us-east-2.amazonaws.com
NEXT_PUBLIC_API_BASE_URL=http://localhost:3000/api

# Allowed Origins
ALLOWED_ORIGINS=http://localhost:3000,https://dual-minds-jg4b4x1a4-bradymcks-projects.vercel.app/

# Super Admin
SUPER_ADMIN_ADDRESSES=0x2026bd9b69593A4002E87049deA6c724654DC38b,0xabcdefabcdefabcdefabcdefabcdefabcdefabcd,0x55608B50C8B3BECC32eD381223BE9C721A8ec782

# Disable telemetry
NEXT_TELEMETRY_DISABLED=1

# Pinata IPFS
PINATA_API_KEY=$(pull "pinata-api-key")
PINATA_API_SECRET=$(pull "pinata-api-secret")
PINATA_SECRET_KEY=$(pull "pinata-api-secret")
PINATA_JWT=$(pull "pinata-jwt")
NEXT_PUBLIC_PINATA_GATEWAY=https://crimson-secret-reindeer-718.mypinata.cloud

# Vercel Cron
CRON_SECRET=$(pull "cron-secret")

# Twitter
TWITTER_API_KEY=$(pull "twitter-api-key")
TWITTER_API_SECRET=$(pull "twitter-api-secret")
TWITTER_ACCESS_TOKEN=$(pull "twitter-access-token")
TWITTER_ACCESS_TOKEN_SECRET=$(pull "twitter-access-token-secret")
ENVFILE

chmod 600 "$ENV_FILE"

if [ "$ERRORS" -gt 0 ]; then
  echo "[hydrate] WARNING: $ERRORS secrets missing from Keychain" >&2
  echo "[hydrate] .env written with MISSING_ placeholders — app may not start correctly" >&2
  exit 1
fi

echo "[hydrate] .env written (mode 600) — all secrets hydrated successfully."
